name       : avidemux
version    : 2.7.6
release    : 33
source     :
    - https://sourceforge.net/projects/avidemux/files/avidemux/2.7.6/avidemux_2.7.6.tar.gz : 9a88741f3535443d4bde35d4207ca2ff96d3b136db2e7232cb50dd6b4eb293cf
license    : GPL-2.0-or-later
component  : multimedia.video
libsplit   : no
summary    : Avidemux is a simple platform video editor
description: |
    Avidemux is a simple platform video editor
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(alsa)
    - pkgconfig(aom)
    - pkgconfig(faad2)
    - pkgconfig(fdk-aac)
    - pkgconfig(ffnvcodec)
    - pkgconfig(glu)
    - pkgconfig(jack)
    - pkgconfig(libass)
    - pkgconfig(libpulse)
    - pkgconfig(libva)
    - pkgconfig(mad)
    - pkgconfig(opus)
    - pkgconfig(samplerate)
    - pkgconfig(sqlite3)
    - pkgconfig(twolame)
    - pkgconfig(vapoursynth)
    - pkgconfig(vdpau)
    - pkgconfig(vorbis)
    - pkgconfig(vpx)
    - pkgconfig(x264)
    - pkgconfig(x265)
    - pkgconfig(xv)
    - lame-devel
    - liba52dec-devel
    - yasm
setup      : |
    chmod +x bootStrap.bash
build      : |
    ./bootStrap.bash \
        --rebuild \
        --without-cli \
        --with-system-liba52 \
        --with-system-libass \
        --with-system-libmad
install    : |
    %make_install -C buildCore
    %make_install -C buildPluginsCommon
    %make_install -C buildQt5
    %make_install -C buildPluginsQt5
