name       : avidemux
version    : 2.7.4
release    : 25
source     :
    - https://github.com/mean00/avidemux2/archive/2.7.4.tar.gz : 2cc0aa6a4ddd5b377bd2ec52c0b3586364c5a6793d149bda9d7ba6b704c84e2a
license    : GPL-2.0-or-later
component  : multimedia.video
libsplit   : no
summary    : Avidemux is a simple platform video editor
description: |
    Avidemux is a simple platform video editor
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(fdk-aac)
    - pkgconfig(ffnvcodec)
    - pkgconfig(glu)
    - pkgconfig(jack)
    - pkgconfig(libass)
    - pkgconfig(libavcodec)
    - pkgconfig(libpulse)
    - pkgconfig(libxslt)
    - pkgconfig(libva)
    - pkgconfig(opus)
    - pkgconfig(sqlite3)
    - pkgconfig(twolame)
    - pkgconfig(vapoursynth)
    - pkgconfig(vorbis)
    - pkgconfig(vdpau)
    - pkgconfig(vpx)
    - pkgconfig(x264)
    - pkgconfig(x265)
    - pkgconfig(xv)
    - faad-devel
    - lame-devel
    - liba52dec-devel
    - libmad-devel
    - yasm
setup      : |
    chmod +x bootStrap.bash
build      : |
    ./bootStrap.bash --with-core --without-cli --with-plugins --rebuild
install    : |
    make -C buildCore DESTDIR=$installdir install
    make -C buildPluginsCommon DESTDIR=$installdir install
    make -C buildQt5 DESTDIR=$installdir install
    make -C buildPluginsQt5 DESTDIR=$installdir install
