name       : avidemux
version    : 2.7.0
release    : 8
source     :
    - https://github.com/mean00/avidemux2/archive/2.7.0.tar.gz : b0941eea6d4bb17c16011fe41624c0117ff024ad6f66cab88673f761b90592c9
license    : GPL-2.0
component  : multimedia.video
libsplit   : no
summary    : Avidemux is a simple platform video editor
description: |
    Avidemux is a simple platform video editor
builddeps  :
    - pkgconfig(fdk-aac)
    - pkgconfig(glu)
    - pkgconfig(Qt5Designer)
    - pkgconfig(libass)
    - pkgconfig(libavcodec)
    - pkgconfig(libpulse)
    - pkgconfig(libxslt)
    - pkgconfig(libva)
    - pkgconfig(opus)
    - pkgconfig(sqlite3)
    - pkgconfig(twolame)
    - pkgconfig(vapoursynth)
    - pkgconfig(vorbis)
    - pkgconfig(vdpau)
    - pkgconfig(vpx)
    - pkgconfig(x264)
    - pkgconfig(x265)
    - pkgconfig(xv)
    - faad-devel
    - lame-devel
    - liba52dec-devel
    - libmad-devel
    - yasm
setup      : |
    chmod +x bootStrap.bash
    cp avidemux2.desktop avidemux-qt.desktop
    sed -ri 's|(Name=).*|\1avidemux (Qt)|' avidemux-qt.desktop
    sed -ri 's|(Exec=).*|\1avidemux3_qt5|' avidemux-qt.desktop
build      : |
    ./bootStrap.bash --with-core --without-cli --with-plugins --rebuild
install    : |
    make -C buildCore DESTDIR=$installdir install
    make -C buildPluginsCommon DESTDIR=$installdir install
    make -C buildQt5 DESTDIR=$installdir install
    make -C buildPluginsQt5 DESTDIR=$installdir install
    install -Dm00644 avidemux_icon.png $installdir/usr/share/pixmaps/avidemux.png
    install -Dm00644 avidemux-qt.desktop $installdir/usr/share/applications/avidemux-qt.desktop
