name       : avidemux
version    : 2.8.0
release    : 41
source     :
    - https://sourceforge.net/projects/avidemux/files/avidemux/2.8.0/avidemux_2.8.0.tar.gz : d1ec6f5277e51228ecf0ee1ca89fae24c591f520f87ce96fabec8818d04de33b
license    : GPL-2.0-or-later
component  : multimedia.video
libsplit   : no
summary    : Avidemux is a simple platform video editor
description: |
    Avidemux is a simple platform video editor
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(alsa)
    - pkgconfig(aom)
    - pkgconfig(faad2)
    - pkgconfig(fdk-aac)
    - pkgconfig(ffnvcodec)
    - pkgconfig(glu)
    - pkgconfig(jack)
    - pkgconfig(libass)
    - pkgconfig(libpulse)
    - pkgconfig(libva)
    - pkgconfig(mad)
    - pkgconfig(opus)
    - pkgconfig(samplerate)
    - pkgconfig(sqlite3)
    - pkgconfig(twolame)
    - pkgconfig(vapoursynth)
    - pkgconfig(vdpau)
    - pkgconfig(vorbis)
    - pkgconfig(vpx)
    - pkgconfig(x264)
    - pkgconfig(x265)
    - pkgconfig(xv)
    - lame-devel
    - liba52dec-devel
    - xvidcore-devel
    - yasm
setup      : |
    chmod +x bootStrap.bash
build      : |
    ./bootStrap.bash \
        --rebuild \
        --without-cli \
        --with-system-liba52 \
        --with-system-libass \
        --with-system-libmad
install    : |
    %make_install -C buildCore
    %make_install -C buildPluginsCommon
    %make_install -C buildQt5
    %make_install -C buildPluginsQt5
