name       : avidemux
version    : 2.6.19
release    : 3
source     :
    - https://solus-project.com/sources/avidemux_2.6.19.tar.gz : c6e5040bf4fc1a06c25a70f1464946b30ce18a48fd9579c26bff6ee7e18d9adb
license    : GPL-2.0
component  : multimedia.video
libsplit   : no
summary    : Avidemux is a simple platform video editor
description: |
    Avidemux is a simple platform video editor
builddeps  :
    - pkgconfig(fdk-aac)
    - pkgconfig(glu)
    - pkgconfig(Qt5Designer)
    - pkgconfig(libass)
    - pkgconfig(libavcodec)
    - pkgconfig(libpulse)
    - pkgconfig(libxslt)
    - pkgconfig(libva)
    - pkgconfig(opus)
    - pkgconfig(sqlite3)
    - pkgconfig(twolame)
    - pkgconfig(vorbis)
    - pkgconfig(vdpau)
    - pkgconfig(vpx)
    - pkgconfig(x264)
    - pkgconfig(x265)
    - pkgconfig(xv)
    - faad-devel
    - lame-devel
    - liba52dec-devel
    - libmad-devel
    - yasm
setup      : |
    chmod +x bootStrap.bash
    cp avidemux2.desktop avidemux-qt.desktop
    sed -ri 's|(Name=).*|\1avidemux (Qt)|' avidemux-qt.desktop
    sed -ri 's|(Exec=).*|\1avidemux3_qt5|' avidemux-qt.desktop
build      : |
    ./bootStrap.bash --with-core --without-cli --with-plugins --rebuild
install    : |
    make -C buildCore DESTDIR=$installdir install
    make -C buildPluginsCommon DESTDIR=$installdir install
    make -C buildQt5 DESTDIR=$installdir install
    make -C buildPluginsQt5 DESTDIR=$installdir install
    install -Dm00644 avidemux_icon.png $installdir/usr/share/pixmaps/avidemux.png
    install -Dm00644 avidemux-qt.desktop $installdir/usr/share/applications/avidemux-qt.desktop
